global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'medical-calculator-monitor'

scrape_configs:
  - job_name: 'fastapi-monitoring'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'monitoring-service'
          environment: 'development'
